# Generated by Django 3.2.4 on 2021-06-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunuz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='dis_like',
        ),
        migrations.RemoveField(
            model_name='new',
            name='like',
        ),
        migrations.RemoveField(
            model_name='new',
            name='views',
        ),
    ]
